### ISSUE TITLE
java.util.regex.PatternSyntaxException

### ISSUE THREAD

**Issue by rkreg** [saaste/play-docker-aws-tutorial#1]
On section 3, when I try to run the "activator docker:stage" command, I get an exception. I'm having trouble finding much online about what to do about it, but I did find an unanswered StackOverflow question: http://stackoverflow.com/questions/34889738/sbt-dockerstage-returns-java-util-regex-patternsyntaxexception-error#comment57698432_34889738.

I'll paste my error down below. Any ideas what could be causing this?

[info] Resolving org.scala-lang#scala-reflect;2.11.6 ...
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which i[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
        at java.util.regex.Pattern.error(Pattern.java:1955)
        at java.util.regex.Pattern.compile(Pattern.java:1702)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2367)
        at java.lang.String.split(String.java:2409)
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:152)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:79)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:70)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:dockerCommands) java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
[error] \
[error]  ^
[error] Total time: 8 s, completed Jan 24, 2016 8:54:10 PM

**Comment by saaste** [comment]
Seems to be related to this bug: https://github.com/sbt/sbt-native-packager/issues/573
Might be good idea to follow this [StackOverflow question](http://stackoverflow.com/questions/34889738/sbt-dockerstage-returns-java-util-regex-patternsyntaxexception-error) since it seems to be Windows issue.
